# Use the AWS Node.js 18 base image for Lambda
FROM public.ecr.aws/lambda/nodejs:18

# Set working directory
WORKDIR /var/task

# Copy package files and install deps
COPY package*.json ./
RUN npm install

# Copy all source code
COPY . .

# Set the handler (file name is app.js and export is lambdaHandler)
CMD ["app.lambdaHandler"]
